package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/gettextcodegen/internal/parser"
	"github.com/gettextcodegen/internal/validator"
)

type Generator struct {
	Package string
	Dir     string
	Entries []*parser.POEntry
}

type Method struct {
	Name        string
	OriginalStr string
	Params      []string
	Body        string
	IsPlural    bool
	HasContext  bool
	Context     string
}

func (g *Generator) Generate() (string, error) {
	var methods []Method
	usedNames := make(map[string]bool)

	for _, entry := range g.Entries {
		ident, err := validator.ToValidIdentifier(entry.MsgID, entry.MsgCtx)
		if err != nil {
			fmt.Printf("Warning: skipping %q: %v\n", entry.MsgID, err)
			continue
		}

		if usedNames[ident] {
			fmt.Printf("Warning: duplicate identifier %q, skipping\n", ident)
			continue
		}
		usedNames[ident] = true

		method := g.buildMethod(ident, entry)
		methods = append(methods, method)
	}

	sort.Slice(methods, func(i, j int) bool {
		return methods[i].Name < methods[j].Name
	})

	return g.render(methods)
}

func (g *Generator) buildMethod(name string, entry *parser.POEntry) Method {
	m := Method{
		Name:        name,
		OriginalStr: entry.MsgID,
		IsPlural:    entry.IsPlural,
		HasContext:  entry.MsgCtx != "",
		Context:     entry.MsgCtx,
	}

	if entry.IsPlural {
		m.Params = []string{"n int"}
		m.Body = g.buildPluralBody(entry)
	} else if len(entry.Variables) > 0 {
		params := make([]string, len(entry.Variables))
		for i, v := range entry.Variables {
			params[i] = fmt.Sprintf("%s %s", v.Name, v.Type)
		}
		m.Params = params
		m.Body = g.buildGetBody(entry)
	} else {
		m.Body = g.buildGetBody(entry)
	}

	return m
}

func (g *Generator) buildGetBody(entry *parser.POEntry) string {
	args := make([]string, len(entry.Variables))
	for i := range entry.Variables {
		args[i] = entry.Variables[i].Name
	}

	if entry.MsgCtx != "" {
		if len(args) == 0 {
			return fmt.Sprintf(`return t.locale.GetC(%q, %q)`, entry.MsgID, entry.MsgCtx)
		}
		return fmt.Sprintf(`return t.locale.GetDC("default", %q, %q, %s)`, entry.MsgID, entry.MsgCtx, strings.Join(args, ", "))
	}

	if len(args) == 0 {
		return fmt.Sprintf(`return t.locale.Get(%q)`, entry.MsgID)
	}
	return fmt.Sprintf(`return t.locale.Get(%q, %s)`, entry.MsgID, strings.Join(args, ", "))
}

func (g *Generator) buildPluralBody(entry *parser.POEntry) string {
	if entry.HasPluralVariables() {
		if entry.MsgCtx != "" {
			return fmt.Sprintf(`if n == 1 {
		return t.locale.GetNC(%q, %q, n, %q)
	}
	return fmt.Sprintf(t.locale.GetNC(%q, %q, n, %q), n)`, entry.MsgID, entry.PluralID, entry.MsgCtx, entry.MsgID, entry.PluralID, entry.MsgCtx)
		}
		return fmt.Sprintf(`if n == 1 {
		return t.locale.GetN(%q, %q, n)
	}
	return fmt.Sprintf(t.locale.GetN(%q, %q, n), n)`, entry.MsgID, entry.PluralID, entry.MsgID, entry.PluralID)
	}
	if entry.MsgCtx != "" {
		return fmt.Sprintf(`return t.locale.GetNC(%q, %q, n, %q)`, entry.MsgID, entry.PluralID, entry.MsgCtx)
	}
	return fmt.Sprintf(`return t.locale.GetN(%q, %q, n)`, entry.MsgID, entry.PluralID)
}

func (g *Generator) render(methods []Method) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by gettextcodegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", g.Package)
	sb.WriteString("import (\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"path/filepath\"\n")
	sb.WriteString("\t\"runtime\"\n\n")
	sb.WriteString("\t\"github.com/leonelquinteros/gotext\"\n")
	sb.WriteString(")\n\n")

	sb.WriteString("type Translator interface {\n")
	for _, m := range methods {
		if m.OriginalStr != "" {
			sb.WriteString(fmt.Sprintf("\t// %q\n", m.OriginalStr))
		}
		sig := m.Name
		if len(m.Params) > 0 {
			sig += "(" + strings.Join(m.Params, ", ") + ")"
		} else {
			sig += "()"
		}
		sig += " string"
		sb.WriteString(fmt.Sprintf("\t%s\n", sig))
	}
	sb.WriteString("}\n\n")

	sb.WriteString("type translator struct {\n")
	sb.WriteString("\tlocale *gotext.Locale\n")
	sb.WriteString("}\n\n")

	sb.WriteString("func New(locale string) (Translator, error) {\n")
	sb.WriteString("\t_, file, _, _ := runtime.Caller(0)\n")
	sb.WriteString("\tlocalesDir := filepath.Dir(file)\n")
	sb.WriteString("\tl := gotext.NewLocale(localesDir, locale)\n")
	sb.WriteString("\tl.AddDomain(\"default\")\n")
	sb.WriteString("\treturn &translator{locale: l}, nil\n")
	sb.WriteString("}\n\n")

	for _, m := range methods {
		sb.WriteString(fmt.Sprintf("func (t *translator) %s", m.Name))
		if len(m.Params) > 0 {
			sb.WriteString("(" + strings.Join(m.Params, ", ") + ")")
		} else {
			sb.WriteString("()")
		}
		sb.WriteString(" string {\n")
		sb.WriteString(fmt.Sprintf("\t%s\n", m.Body))
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}