package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Glootea/gettextgocodegen/internal/parser"
	"github.com/Glootea/gettextgocodegen/internal/validator"
)

type Generator struct {
	Package   string
	Dir       string
	Entries   []*parser.POEntry
	Languages []string
}

type Method struct {
	Name        string
	OriginalStr string
	Params      []string
	Body        string
	IsPlural    bool
	HasContext  bool
	Context     string
}

func (g *Generator) Generate() (string, error) {
	identifierCache = make(map[*parser.POEntry]string)

	sort.Slice(g.Entries, func(i, j int) bool {
		identI := cachedIdentifier(g.Entries[i])
		identJ := cachedIdentifier(g.Entries[j])
		if identI != identJ {
			return identI < identJ
		}
		if g.Entries[i].MsgCtx != g.Entries[j].MsgCtx {
			return g.Entries[i].MsgCtx < g.Entries[j].MsgCtx
		}
		return g.Entries[i].MsgID < g.Entries[j].MsgID
	})

	var methods []Method
	usedNames := make(map[string]bool)
	hasFmt := false
	for _, entry := range g.Entries {
		ident := cachedIdentifier(entry)
		if ident == "" {
			fmt.Printf("Warning: skipping %q: cannot convert to valid identifier\n", entry.MsgID)
			continue
		}

		if usedNames[ident] {
			fmt.Printf("Warning: duplicate identifier %q, skipping\n", ident)
			continue
		}
		usedNames[ident] = true

		method, hasFmtLocal := g.buildMethod(ident, entry)
		methods = append(methods, method)
		hasFmt = hasFmt || hasFmtLocal
	}

	return g.render(methods, hasFmt)
}

var identifierCache = make(map[*parser.POEntry]string)

func cachedIdentifier(entry *parser.POEntry) string {
	if ident, ok := identifierCache[entry]; ok {
		return ident
	}
	ident, _ := validator.ToValidIdentifier(entry.MsgID, entry.MsgCtx)
	identifierCache[entry] = ident
	return ident
}

func (g *Generator) buildMethod(name string, entry *parser.POEntry) (Method, bool) {
	m := Method{
		Name:        name,
		OriginalStr: entry.MsgID,
		IsPlural:    entry.IsPlural,
		HasContext:  entry.MsgCtx != "",
		Context:     entry.MsgCtx,
	}
	hasFmt := false

	if entry.IsPlural {
		m.Params = []string{"n int"}
		hasFmtLocal := false
		m.Body, hasFmtLocal = g.buildPluralBody(entry)
		hasFmt = hasFmt || hasFmtLocal
	} else if len(entry.Variables) > 0 {
		params := make([]string, len(entry.Variables))
		for i, v := range entry.Variables {
			params[i] = fmt.Sprintf("%s %s", v.Name, v.Type)
		}
		m.Params = params
		m.Body = g.buildGetBody(entry)
	} else {
		m.Body = g.buildGetBody(entry)
	}

	return m, hasFmt
}

func (g *Generator) buildGetBody(entry *parser.POEntry) string {
	args := make([]string, len(entry.Variables))
	for i := range entry.Variables {
		args[i] = entry.Variables[i].Name
	}

	if entry.MsgCtx != "" {
		if len(args) == 0 {
			return fmt.Sprintf(`return t.locale.GetC(%q, %q)`, entry.MsgID, entry.MsgCtx)
		}
		return fmt.Sprintf(`return t.locale.GetDC("default", %q, %q, %s)`, entry.MsgID, entry.MsgCtx, strings.Join(args, ", "))
	}

	if len(args) == 0 {
		return fmt.Sprintf(`return t.locale.Get(%q)`, entry.MsgID)
	}
	return fmt.Sprintf(`return t.locale.Get(%q, %s)`, entry.MsgID, strings.Join(args, ", "))
}

func (g *Generator) buildPluralBody(entry *parser.POEntry) (string, bool) {
	if entry.HasPluralVariables() {
		if entry.MsgCtx != "" {
			return fmt.Sprintf(`if n == 1 {
		return t.locale.GetNC(%q, %q, n, %q)
	}
	return fmt.Sprintf(t.locale.GetNC(%q, %q, n, %q), n)`, entry.MsgID, entry.PluralID, entry.MsgCtx, entry.MsgID, entry.PluralID, entry.MsgCtx), true
		}
		return fmt.Sprintf(`if n == 1 {
		return t.locale.GetN(%q, %q, n)
	}
	return fmt.Sprintf(t.locale.GetN(%q, %q, n), n)`, entry.MsgID, entry.PluralID, entry.MsgID, entry.PluralID), true
	}
	if entry.MsgCtx != "" {
		return fmt.Sprintf(`return t.locale.GetNC(%q, %q, n, %q)`, entry.MsgID, entry.PluralID, entry.MsgCtx), false
	}
	return fmt.Sprintf(`return t.locale.GetN(%q, %q, n)`, entry.MsgID, entry.PluralID), false
}

func (g *Generator) render(methods []Method, hasFmt bool) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by gettextcodegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&sb, "package %s\n\n", g.Package)
	sb.WriteString("import (\n")
	if hasFmt {
		sb.WriteString("\t\"fmt\"\n")
	}
	sb.WriteString("\t\"path/filepath\"\n")
	sb.WriteString("\t\"runtime\"\n\n")
	sb.WriteString("\t\"github.com/leonelquinteros/gotext\"\n")
	sb.WriteString(")\n\n")

	sb.WriteString("type Locale string\n\n")
	sb.WriteString("const (\n")
	sb.WriteString("\tLocaleInvalid Locale = \"\"\n")
	for _, lang := range g.Languages {
		fmt.Fprintf(&sb, "\tLocale%s Locale = %q\n", toLocaleName(lang), lang)
	}
	sb.WriteString(")\n\n")

	sb.WriteString("type Translator interface {\n")
	for _, m := range methods {
		if m.OriginalStr != "" {
			fmt.Fprintf(&sb, "\t// %q\n", m.OriginalStr)
		}
		sig := m.Name
		if len(m.Params) > 0 {
			sig += "(" + strings.Join(m.Params, ", ") + ")"
		} else {
			sig += "()"
		}
		sig += " string"
		fmt.Fprintf(&sb, "\t%s\n", sig)
	}
	sb.WriteString("}\n\n")

	sb.WriteString("type translator struct {\n")
	sb.WriteString("\tlocale *gotext.Locale\n")
	sb.WriteString("}\n\n")

	sb.WriteString("func New(locale Locale) (Translator, error) {\n")
	sb.WriteString("\t_, file, _, _ := runtime.Caller(0)\n")
	sb.WriteString("\tlocalesDir := filepath.Dir(file)\n")
	sb.WriteString("\tl := gotext.NewLocale(localesDir, string(locale))\n")
	sb.WriteString("\tl.AddDomain(\"default\")\n")
	sb.WriteString("\treturn &translator{locale: l}, nil\n")
	sb.WriteString("}\n\n")

	for _, m := range methods {
		fmt.Fprintf(&sb, "func (t *translator) %s", m.Name)
		if len(m.Params) > 0 {
			sb.WriteString("(" + strings.Join(m.Params, ", ") + ")")
		} else {
			sb.WriteString("()")
		}
		sb.WriteString(" string {\n")
		fmt.Fprintf(&sb, "\t%s\n", m.Body)
		sb.WriteString("}\n\n")
	}

	return sb.String(), nil
}

func toLocaleName(lang string) string {
	lang = strings.ReplaceAll(lang, "-", "")
	lang = strings.ReplaceAll(lang, "_", "")
	if len(lang) > 0 {
		return strings.ToUpper(lang[:1]) + lang[1:]
	}
	return lang
}
