// Code generated by gettextcodegen. DO NOT EDIT.

package translations

import (
	"fmt"
	"path/filepath"
	"runtime"

	"github.com/leonelquinteros/gotext"
)

type Locale string

const (
	LocaleInvalid Locale = ""
	LocaleEnUS    Locale = "en_US"
	LocaleRuRU    Locale = "ru_RU"
)

type Translator interface {
	// "Cancel"
	ButtonsCancel() string
	// "Submit"
	ButtonsSubmit() string
	// "Add to cart"
	CartAddToCart() string
	// "Total: %s"
	CartTotal(param1 string) string
	// "File not found"
	ErrorsFileNotFound() string
	// "Get items count"
	GetItemsCount(n int) string
	// "Hello world"
	HelloWorld() string
	// "Hi, my name is %s"
	HiMyNameIs(param1 string) string
	// "Welcome to our app!"
	WelcomeToOurApp() string
}

type translator struct {
	locale *gotext.Locale
}

func New(locale Locale) (Translator, error) {
	_, file, _, _ := runtime.Caller(0)
	localesDir := filepath.Dir(file)
	l := gotext.NewLocale(localesDir, string(locale))
	l.AddDomain("default")
	return &translator{locale: l}, nil
}

func (t *translator) ButtonsCancel() string {
	return t.locale.GetC("Cancel", "buttons")
}

func (t *translator) ButtonsSubmit() string {
	return t.locale.GetC("Submit", "buttons")
}

func (t *translator) CartAddToCart() string {
	return t.locale.GetC("Add to cart", "cart")
}

func (t *translator) CartTotal(param1 string) string {
	return t.locale.GetDC("default", "Total: %s", "cart", param1)
}

func (t *translator) ErrorsFileNotFound() string {
	return t.locale.GetC("File not found", "errors")
}

func (t *translator) GetItemsCount(n int) string {
	if n == 1 {
		return t.locale.GetN("Get items count", "%d items", n)
	}
	return fmt.Sprintf(t.locale.GetN("Get items count", "%d items", n), n)
}

func (t *translator) HelloWorld() string {
	return t.locale.Get("Hello world")
}

func (t *translator) HiMyNameIs(param1 string) string {
	return t.locale.Get("Hi, my name is %s", param1)
}

func (t *translator) WelcomeToOurApp() string {
	return t.locale.Get("Welcome to our app!")
}
